---
- hosts:
  - kaspbeerypi
  become: yes
  vars:
    apt_pkgs:
      - gcc
      - bluez
      - libbluetooth-dev
  tasks:
    - name: "apt full-upgrade"
      apt:
        update_cache: yes
        upgrade: full

    - name: "Install system packages"
      apt:
        name: "{{ apt_pkgs }}"
        state: present
        force_apt_get: "yes"

- hosts:
  - kaspbeerypi
  become: yes
  vars:
    pip_install_packages:
      - dropbox==11.16.0
      - interruptingcow==0.8
      - w1thermsensor==2.0.0
      - pybluez==0.23
      - scrollphathd==1.3.0
      - schedule==1.1.0
  roles:
    - geerlingguy.pip
  tasks:
    - name: Create /opt/logFermentation/ folder
      file:
        path: /opt/logFermentation/
        state: directory
        mode: 0755

    - name: Copy python scripts
      copy:
        src: "{{ item }}"
        dest: /opt/logFermentation/
        owner: root
        group: root
        mode: 0755
      with_items:
        - logFermentation/blescan.py
        - logFermentation/readsensors.py
        - logFermentation/scrollit.py

    - name: Copy variables file for python scripts
      template:
        src: "logFermentation/vars.py.j2"
        dest: "/opt/logFermentation/vars.py"
        mode: 0755

    # - name: Copy readsensors systemd service file
    #   copy:
    #     src: readsensors.service
    #     dest: /etc/systemd/system
    #     owner: root
    #     group: root
    #     mode: 0755

    # - name: Start readsensors
    #   systemd:
    #     name: readsensors
    #     state: started
    #     enabled: yes