---
- hosts:
  - all
  become: yes
  vars:
    apt_pkgs:
      - gcc
      - bluez
      - libbluetooth-dev
      - python3-pip
  tasks:
    - name: "apt full-upgrade"
      apt:
        update_cache: yes
        upgrade: full

    - name: "Install system packages"
      apt:
        name: "{{ apt_pkgs }}"
        state: present
        force_apt_get: "yes"

- hosts:
  - all
  become: yes
  vars_files:
    - ansible_vars.yml
  vars:
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - dropbox
      - interruptingcow
      - w1thermsensor
      - pybluez
      - scrollphathd
      - schedule
  roles:
    - geerlingguy.pip
  tasks:
    - name: Create /opt/logFermentation/ folder
      file:
        path: /opt/logFermentation/
        state: directory
        mode: 0755

    - name: Copy python scripts
      copy:
        src: "{{ item }}"
        dest: /opt/logFermentation/
        owner: root
        group: root
        mode: 0755
      with_items:
        - logFermentation/blescan.py
        - logFermentation/readsensors.py
        - logFermentation/scrollit.py

    - name: Copy variables file for python scripts
      template:
        src: "logFermentation/vars.py.j2"
        dest: "/opt/logFermentation/vars.py"
        mode: 0755

    - name: Copy systemd service files
      copy:
        src: "{{ item }}"
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: 0755
      with_items:
        - logFermentation/readsensors.service
        - logFermentation/scrollit.service

    - name: Start readsensors
      systemd:
        name: readsensors
        state: started
        enabled: yes