- name: Create /opt/logFermentation/ folder
  file:
    path: /opt/logFermentation/
    state: directory
    mode: 0755

- name: Copy python scripts
  copy:
    src: "{{ item }}"
    dest: /opt/logFermentation/
    owner: root
    group: root
    mode: 0755
  with_items:
    - blescan.py
    - readsensors.py
    - scrollit.py

- name: Copy variables file for python scripts
  template:
    src: "files/vars.py.j2"
    dest: "/opt/logFermentation/vars.py"
    mode: 0755

# - name: Copy readsensors systemd service file
#   copy:
#     src: readsensors.service
#     dest: /etc/systemd/system
#     owner: root
#     group: root
#     mode: 0755

# - name: Start readsensors
#   systemd:
#     name: readsensors
#     state: started
#     enabled: yes