---
- hosts:
  - all
  become: yes
  vars:
    apt_pkgs:
      - gcc
      - bluez
      - libbluetooth-dev
  tasks:
    - name: "apt full-upgrade"
      apt:
        update_cache: yes
        upgrade: full

    - name: "Install system packages"
      apt:
        name: "{{ apt_pkgs }}"
        state: present
        force_apt_get: "yes"

- hosts:
  - all
  become: yes
  vars:
    pip_install_packages:
      - dropbox==11.16.0
      - interruptingcow==0.8
      - w1thermsensor==2.0.0
      - pybluez==0.23
      - scrollphathd==1.3.0
      - schedule==1.1.0
  roles:
    - geerlingguy.pip
    - logFermentation